DSC:
    midway2:
        description: UChicago RCC cluster Midway 2
        address: localhost
        paths:
            home: /home/jeanm
        queue_type: pbs
        status_check_interval: 120
        max_running_jobs: 90 
        max_cores: 40
        max_mem: 57G
        job_template: |
            #!/bin/bash
            #SBATCH --time={walltime}
            #SBATCH --nodes={nodes}
            #SBATCH --cpus-per-task={cores}
            #SBATCH --partition=broadwl
            #SBATCH --account pi-xinhe
            #SBATCH --mem={mem//10**9}G
            #SBATCH --job-name={job_name}
            #SBATCH --output={cur_dir}/{job_name}.out
            #SBATCH --error={cur_dir}/{job_name}.err
            cd {cur_dir}
            module load R
        submit_cmd: sbatch {job_file}
        submit_cmd_output: "Submitted batch job {job_id}"
        status_cmd: squeue --job {job_id}
        kill_cmd: scancel {job_id}

default:
    queue: midway2
    instances_per_job: 30
    nodes_per_job: 1
    cpus_per_node: 4
    cpus_per_instance: 1
    mem_per_instance: 10G
    time_per_instance: 20m

simulate:
    cpus_per_instance: 4

cause:
    instances_per_job: 10
    cpus_per_instance: 4 
    time_per_instance: 2:00:00

cause_params:
    instances_per_job: 10 
    cpus_per_instance: 4 
    time_per_instance: 2:00:00

mr:
    instances_per_job: 40
    time_per_instance: 50m

